apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bespinian/argocd-demo.git
    targetRevision: HEAD
    path: env/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: awesome-gitops-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
