apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-app-deployment
  labels:
    app: awesome-app
spec:
  replicas: 3
  selector:
    matchLabels:
      component: awesome-app
  template:
    metadata:
      labels:
        component: awesome-app
    spec:
      serviceAccountName: awesome-app-sa
      containers:
        - name: awesome-app
          image: bespinian/awesome-image:1.0.0
          imagePullPolicy: Always
          env:
            - name: APP_TITLE
              value: Something awesome!
            - name: DB_HOST
              value: db.bespinian.io
            - name: APP_VERSION
              value: 1.0.0
          ports:
            - containerPort: 8080
